### ISSUE TITLE
Issue with MSD 

### ISSUE THREAD

**Issue by thienbinh92** [materialsvirtuallab/pymatgen-analysis-diffusion#317]
Hi, I think the MSD calculation is incorrect. I obtained the smearing, and spiky MSD for the smooth option = False. Because we need to find the fitting slope from MSD(t) line, it is hard to find the best fitting time lag from the spiky MSD. Maybe a function log(MSD) vs log(t) should be introduced to find the ballistic or diffusive regime, which can not see from a spiky MSD. The user should have an option to choose a suitable time for estimating slop, and diffusivity because the tail of MSD is often removed.
Note: It is surprising that I got the different MSD lines from the same MD output files using the same MSD equation. (compared with MSD obtained from VASPKIT, or [Yfei Mo code](https://github.com/mogroupumd/aimd))
<img width="852" alt="Screenshot 0004-08-07 at 19 24 37" src="https://user-images.githubusercontent.com/56110825/183286505-b85240ac-05ae-420c-ba8e-94429cb23309.png">

**Comment by shyuep** [comment]
Pls clarify exactly why the MSD calculation is "incorrect"? Plotting a log-log plot is simply a matter of changing the axes to a log axis in matplotlib. That can be done directly in your code. 

In the end, we can only look at issues where a comprehensive error report is given. For instance, if saying that the MSD plots by two codes are different, at the minimum we need to see the two plots and a version of the output file. Otherwise we cannot even reproduce the issue, much less explore corrections (if any).

**Comment by thienbinh92** [comment]
Dear Prof, I appreciate your response. I am not sure I understand your developed code completely, for example, these lines:
```                      
for i, n in enumerate(timesteps):
    if not smoothed:
        dx = dc[:, i : i + 1, :]
        dcomponents = dc[:, i : i + 1, :]
```
I think it is incorrect because it is not easy to see the slope or the ballistic/diffusive regime. I obtain a spiky MSD line using PYMATGEN while it is a line with a clear slope from VASPKIT.  The spiky one may lead to misleading conclusions such as the phase transition, reactions, etc.
I think log(MSD) vs log(t) is an option that helps the users know whether a trajectory is "long enough". In addition, I found the dimensional factor set of 3 (MSD slope / 60). But in some cases, for 2D materials, dim=2 is applied (D=MSD slope / 40). Maybe an option of dimensional factor is necessary as well.
<img width="1055" alt="Screenshot 0004-08-08 at 22 28 32" src="https://user-images.githubusercontent.com/56110825/183430440-6127c245-4c98-44b9-96b8-68928c9f0783.png">

**Comment by VvVLzy** [comment]
I think the the jagged MSD is simply due to the fact that you choose to plot it without any smoothing. When you set `smoothed=None` you are essentially plotting the raw data points: that is, the square of your displacements at each time step; the line is simply connecting all the discretized points at each time step without any averaging, hence it looked jagged. The other two lines you've shown seems smoothed with some other algorithms. You can try to set `smoothed=max` or `smoothed=constant` and see how that changes your MSD. I think `smoothed=constant` is simply taking a dynamic average, but I am less sure about what `smoothed=max` is doing behind the scene.

Note also that how you smooth the MSD will affect the final extrapolated diffusivity. The calculation of diffusivity is basically done by doing least square regression on your smoothed MSD. In reality, you might want to determine on your own which part of the MSD you want to use to do that linear regression.

**Comment by shyuep** [comment]
@VvVLzy is correct. It is up to you how you want to smooth the MSD. This is mainly for presentation purposes.

While there might be some small changes in the diffusivity with smoothing, the values are usually not all that different.

**Comment by thienbinh92** [comment]
Thank you for your response. I am still concerned about the smoothing parameters. I found that MSD can be calculated using FFT techniques without smoothing parameters from this StackOverflow link [FFT_MSD](https://stackoverflow.com/questions/34222272/computing-mean-square-displacement-using-python-and-fft). Maybe this is the better way to calculate MSD.
<img width="611" alt="Screenshot 0004-09-28 at 22 45 01" src="https://user-images.githubusercontent.com/56110825/192796287-87befce6-1a09-42b1-be81-ac79b611184b.png">
